<template>
	<div>
		<transition name="el-zoom-in-center">
		<div class="maxbox slide-in-elliptic-top-fwd">
			
			<div class="boxleft">
				<img src="../assets/login_bg.4781e8d2.png" alt="" width="100%" height="100%">
			</div>
			<div class="boxright">
				<el-radio-group v-model="zhuangtai" size="medium" class="button" border>
					<el-radio-button label="denglu"    >登录</el-radio-button>
					<el-radio-button label="zhuce"  >注册</el-radio-button>
				</el-radio-group>
				<el-form label-width="150px" class="from">
					<el-form-item label="学 号" label-width="70px">
					<el-input type="text" v-model="xuehao" maxlength=10></el-input>
					</el-form-item>
					<el-form-item label="姓 名" label-width="70px">
					<el-input type="text" v-model="username"></el-input>
					</el-form-item>
					<el-form-item label="口 令" label-width="70px">
					<el-input type="text" v-model="password" show-password></el-input>
					</el-form-item>
				</el-form>
				<div class="buttonbox">
					<el-button type="primary" size="small" @click="submit" > 提 交 </el-button>
					<el-button size="small" plain @click="reset"> 重 置 </el-button>
				</div>
				
			</div>

			
		</div>
		
		</transition>
		<el-col :sm="12" :lg="6" v-show="succ">
				<el-result icon="success" title="登录成功" subTitle="正在跳转页面">
				
				</el-result>
		</el-col>
	</div>
	

</template>

<script>
// import { Message } from 'element-ui';
export default {
	name:"login",
	data(){
		return{
			xuehao:"",
			username:"",
			password:"",
			zhuangtai:"denglu",
			succ:false
		}

	},
	
	methods:{
		submit(){
			console.log(this.zhuangtai)
			// axios 发送请求
			if(!this.username || !this.password || !this.xuehao)
			{
				alert("信息不完整！😠")
				return 
			}

			//登录接口
			if(this.zhuangtai=="denglu" ){
				let that = this
				this.axios.post('https://qcakyo.fn.thelarkcloud.com/login', {
				xuehao:this.xuehao,
				username: this.username,
				password:this.password,
				banji:"web2"
				
				})
				.then(function (response) {
					
					console.log(response);
					console.log(response.data.ans[0]._id)
					
					if(response.data.ans=="-1"){
						alert("登录失败😭，检查下账号密码吧！")
					}else{
						localStorage.setItem("_id",response.data.ans[0]._id)
						localStorage.setItem("username",response.data.ans[0].username)
						localStorage.setItem("password",response.data.ans[0].password)
						localStorage.setItem("xuehao",response.data.ans[0].xuehao)
						localStorage.setItem("admin",response.data.ans[0].admin)
						localStorage.setItem("banji","web2")
						localStorage.setItem("times","0")
						alert("登录成功😁！")
						// console.log("--->this",that)
						that.succ=true
						that.$router.replace({
							path:"/info"
						})

					}
					

					// 提示消息  (没有实现) 待完成
					
					// this.$message({
					// 	message: '恭喜你，这是一条成功消息',
					// 	type: 'success'
					// });
				})
				.catch(function (error) {
					console.log(error);
					
				});

			}else{
				//注册接口

				this.axios.post('https://qcakyo.fn.thelarkcloud.com/adduser', {
				xuehao:this.xuehao,
				username: this.username,
				password:this.password,
				banji:"web2"
				
				})
				.then(function (response) {
					console.log(response);
					alert("注册成功😊！请前往登录。")

					// 提示消息  (没有实现) 待完成
					
					// this.$message({
					// 	message: '恭喜你，这是一条成功消息',
					// 	type: 'success'
					// });
				})
				.catch(function (error) {
					console.log(error);
				});
				}
			
		},

		//重制函数
		reset(){
			this.xuehao="",
			this.username="",
			this.password=""
		}
		
	}
}
</script>

<style>



	.maxbox{
		margin: 100px auto;
		
		width: 50%;
		height: 50%;
		/* border: black solid 1px; */
		border-radius: 2%;
		display: flex;
		flex-wrap: nowrap;
		box-shadow:0 0 10px rgb(126, 126, 126);
		

	
		
		
	}

	.slide-in-elliptic-top-fwd{-webkit-animation:slide-in-elliptic-top-fwd 2s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-elliptic-top-fwd 2s cubic-bezier(.25,.46,.45,.94) both}
	/* ----------------------------------------------
	* Generated by Animista on 2021-8-31 9:28:23
	* Licensed under FreeBSD License.
	* See http://animista.net/license for more info. 
	* w: http://animista.net, t: @cssanimista
	* ---------------------------------------------- */

	@-webkit-keyframes slide-in-elliptic-top-fwd{0%{-webkit-transform:translateY(-600px) rotateX(-30deg) scale(0);transform:translateY(-600px) rotateX(-30deg) scale(0);-webkit-transform-origin:50% 100%;transform-origin:50% 100%;opacity:0}100%{-webkit-transform:translateY(0) rotateX(0) scale(1);transform:translateY(0) rotateX(0) scale(1);-webkit-transform-origin:50% 1400px;transform-origin:50% 1400px;opacity:1}}@keyframes slide-in-elliptic-top-fwd{0%{-webkit-transform:translateY(-600px) rotateX(-30deg) scale(0);transform:translateY(-600px) rotateX(-30deg) scale(0);-webkit-transform-origin:50% 100%;transform-origin:50% 100%;opacity:0}100%{-webkit-transform:translateY(0) rotateX(0) scale(1);transform:translateY(0) rotateX(0) scale(1);-webkit-transform-origin:50% 1400px;transform-origin:50% 1400px;opacity:1}}
	/* 添加动画1 从左往右开抽屉 */
	.scale-up-hor-left {
		-webkit-animation: scale-up-hor-left 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
		animation: scale-up-hor-left 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	}
	@keyframes scale-up-hor-left {
		0% {
			transform: scaleX(0.4);
			transform-origin: 0% 0%;
		}
		100% {
			transform: scaleX(1);
			transform-origin: 0% 0%;
		}
	}


	.boxleft{
		/* border: solid green 1px; */
		width: 50%;
		height: 100%;
	}
	.boxright{
		padding-top: 10%;
	}
	.anniu{
		margin: 5px;
	}
	.button{
		margin-top: 30px;
		margin-left: 30%;
		/* border: indianred solid 1px; */
	}
	.from{
		/* width: 50%; */
		margin-top: 20px;
		/* width: 100%; */
		width: 320px;
		/* border: 1px solid red; */
		
	}
	.buttonbox{
		/* border: solid 1px olive; */
		display: flex;
		justify-content:center;
	}
	
</style>